# Generated by Django 5.0.1 on 2024-01-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('count_seats', models.IntegerField()),
                ('is_social', models.BooleanField(default=False)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=19)),
                ('is_net_object', models.BooleanField()),
                ('phone_number', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('cite', models.CharField(max_length=100)),
            ],
        ),
    ]
