# Generated by Django 5.0.1 on 2024-01-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polyclinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('bed_fund', models.TextField()),
                ('is_price', models.BooleanField()),
                ('is_pharmacy_kiosk', models.BooleanField()),
                ('is_ambulance', models.BooleanField()),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=19)),
            ],
        ),
    ]
