# Generated by Django 5.0.1 on 2024-01-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_polyclinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClustersBundels',
            fields=[
                ('type', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=17, max_digits=19, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=17, max_digits=19, null=True)),
                ('cluster', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clusters_bundels',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='phone_number',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
