# Generated by Django 5.0.1 on 2024-01-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_clustersbundels_polyclinic_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterArchive',
            fields=[
                ('type', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('date_archive', models.DateField()),
            ],
            options={
                'db_table': 'cluster_archive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cluster_name',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='food',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
