# Generated by Django 5.0.1 on 2024-01-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_clusterarchive_name_food_address_polyclinic_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameIncreased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=4, null=True)),
                ('id_increased', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cluster_name_increased',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='clustersbundels',
            options={},
        ),
    ]
